// Generated by CoffeeScript 1.3.1

module.exports = {
  "**::tropo::sendSMS": function(data, callback) {
    return this.sendSMSEventReceived(data.messageBody, data.senderPhoneNumber, data.recipientPhoneNumber, callback);
  },
  "**::tropo::getNumberForAreaCode": function(data, callback) {
    return this.getNumberForAreaCode(data.areaCode, callback);
  },
  "**::tropo::listAreaCodesInPool": function(data, callback) {
    return this.listAreaCodesInPool(callback);
  }
};
